### ISSUE TITLE
Repo needs to be updated to dotnet 5.0

### ISSUE THREAD

**Issue by brnhensley** [epicodus-lessons/csharp-friend-letter#1]
All the branches are still using:

```xml
<TargetFramework>netcoreapp2.2</TargetFramework>
```

**Comment by kullb3rg** [comment]
Hey Brian! I've updated the target frame work, however this is not the repo we are using anymore!

There's a new one for .NET 5: https://github.com/epicodus-lessons/csharp-friend-letter-dotnet-5

**Comment by brnhensley** [comment]
whoops, thanks for the update!
